#!/bin/bash
clear 
file=.phonebookDB.txt
i=0

if [ ! -f "$file" ]
then
touch .phonebookDB.txt
fi

$name1
$name2 
$phone1
$phone2
$cont
$choice
$searchVar
$cont
$answer

cont=0


echo 'Hello To My PhoneBook ;)'
 


if [[ $1 = "-i" ]]
then

namenumber1=40
while [[ namenumber1 -ge 20 ]] || [[ namenumber2 -ge 20 ]]
do
echo 'Enter Ur First Name :'
read name1 
namenumber1=${#name1}

echo 'Enter Ur Last Name :'
read name2 
namenumber2=${#name2}

echo 'Enter Ur Phone Number :'
read phone1 
if [[ $phone1 =~ ^[0-9]+$ ]]
then
flag1=1
else
flag1=0
fi
while [[ ${#phone1} -ne 11 ]] || [[ flag1 -eq 0 ]]
do
echo "The phone number must be 11 number and must be numbers only"
read phone1
if [[ $phone1 =~ ^[0-9]+$ ]]
then
flag1=1
else
flag1=0
fi
done
echo 'Do You Want To Add Another Number ? y/n :'
read answer

if [ $answer = "y" ]
then
echo 'Enter Ur Phone Number :'
read phone2
if [[ $phone2 =~ ^[0-9]+$ ]]
then
flag=1
else
flag=0
fi

while [[ ${#phone2} -ne 11 ]] || [[ flag -eq 0 ]] 
do
echo "The phone number must be 11 number and must be numbers only"
read phone2
if [[ $phone2 =~ ^[0-9]+$ ]]
then
flag=1
else
flag=0
fi
done
fi

done
echo $name1 $name2 $phone1 $phone2 >> .phonebookDB.txt

echo 'Contact Was Added Successfully '


elif [[ $1 = "-v" ]]
then
echo 'All Contacts Are :'
cat $file | while read line ; do
i=$[ $i +1 ]
echo "$i $line"
done


elif [[ $1 = "-s" ]]
then
echo 'Please Enter The First Name or Last Name or Number:'
read searchVar 
result=$(grep $searchVar $file)
if [ -z "$result" ]
then
echo "No Record Found ! "
else 
grep $searchVar $file | while read -r line ; do
i=$[ $i +1 ]
echo "$i $line"
done
fi

elif [[ $1 = "-e" ]]
then
cat /dev/null > .phonebookDB.txt
echo 'All Contacts Was Deleted Successfully :D'


elif [[ $1 = "-d" ]]
then
echo "Please Enter The First Name or Last Name or Number:"
read searchVar
result=$(grep "$searchVar" $file)
if [ -z "$result" ]
then
echo "No Record Found ! "

else
grep "$searchVar" $file | while read -r line ; do
i=$[ $i +1 ]
echo "$i $line"
done

echo "Enter The Number Of Record You Want To Delete : " 
read Num
i=0
grep $searchVar $file | while read -r line ; do
i=$[ $i +1 ]
if [ $Num -eq $i ] ;then
echo "`sed  /"$line"/d  $file`" > $file
fi
done
fi 
#sed -i "/$searchVar/d" .phonebookDB.txt

elif [[ $1 = "" ]]
then
echo 'Please Select an Option when you run the phoneBook Script :'
echo '(-i)-To Insert New Contact'
echo '(-v)-To View All Contacts'
echo '(-s)-To Search By Name'
echo '(-e)-To Delete All Contacts'
echo '(-d)-To Delete One Record'

else
exit

fi 
echo "------------------------------------------"
 



